title: FreeGamesOnline.ee
description: Play the best free online games - FreeGamesOnline.ee
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  games:
    output: true
